os: linux

# branches:
#   only:
#     - develop
#     - travis
#     - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

language: go

go:
  - "1.11"

python:
  -"3.6"

addons:
  apt:
    packages:
      - flawfinder
      - squashfs-tools
      - uuid-dev
      - libuuid1
      - libffi-dev
      - libssl-dev
      - libssl1.0.0
      - libarchive-dev
      - libgpgme11-dev
      - libseccomp-dev
  homebrew:
    packages:
      - squashfs
    update: true

sudo: required

matrix:
  include:
    - python: "3.6"

before_install:
  # Install Singularity
  - sudo chmod u+x .travis/*.sh
  - /bin/bash .travis/setup.sh

before_script:
  - singularity pull --allow-unauthenticated local.simg library://temigo/default/lartpc_mlreco3d:sha256.2f2b3011371e109db83e21b556d3d82f21b639acad4a412589429e9b9abc53de

script:
  - singularity exec local.simg pip3 install pytest --user
  - singularity exec local.simg pytest test
